# Generated by Django 4.0.1 on 2022-01-26 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('plant_care', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Plants',
            },
        ),
        migrations.CreateModel(
            name='PlantCommonName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.plant', verbose_name='Plant')),
            ],
            options={
                'verbose_name_plural': 'Plant Common Names',
            },
        ),
    ]
