# Generated by Django 4.0.1 on 2022-01-26 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='scientific_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='UserPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_for_sale', models.BooleanField(default=False)),
                ('is_for_trade', models.BooleanField(default=False)),
                ('is_for_pickup', models.BooleanField(default=False)),
                ('is_for_shipping', models.BooleanField(default=False)),
                ('image_url', models.CharField(max_length=512)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='plant.plant', verbose_name='Plant')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': "User's Plants",
            },
        ),
    ]
