# Generated by Django 4.0.1 on 2022-01-27 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plant', '0002_alter_plant_scientific_name_userplant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcommonname',
            name='plant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getCommonNames', to='plant.plant', verbose_name='Plant'),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='plant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='getUserPlants', to='plant.plant', verbose_name='Plant'),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='getUserPlants', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
