# Generated by Django 4.0.1 on 2022-01-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_alter_plantcommonname_plant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='comment',
            field=models.TextField(blank=True, help_text='Share some info about your plant!'),
        ),
        migrations.AddField(
            model_name='userplant',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
