# Generated by Django 4.0.1 on 2022-01-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_userplant_comment_userplant_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplant',
            name='image_url',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
