# Generated by Django 4.0.1 on 2022-01-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_alter_userplant_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantcommonname',
            old_name='plant_id',
            new_name='plant',
        ),
        migrations.RenameField(
            model_name='userplant',
            old_name='plant_id',
            new_name='plant',
        ),
        migrations.RenameField(
            model_name='userplant',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=models.TextField(help_text='Describe the plant'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_care',
            field=models.TextField(help_text='Share some care info\nLight:\nWater:\nFertilizer:\nTemperature:\nHumidity:\nSoil:\nPot:\nPruning:\nPropagation:\nPoisonous Plant Info:\n'),
        ),
    ]
