# Generated by Django 4.0.1 on 2022-01-27 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plant', '0006_rename_plant_id_plantcommonname_plant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcommonname',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_common_names', to='plant.plant', verbose_name='Plant'),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='get_user_plants', to='plant.plant', verbose_name='Plant'),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_user_plants', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
