# Generated by Django 4.0.1 on 2022-02-03 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plant', '0002_alter_plantcommonname_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('trade_status', models.CharField(choices=[('SE', 'sent'), ('AC', 'accepted'), ('RE', 'rejected'), ('UN', 'unavailable')], default='SE', max_length=2)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_buyer_trades', to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_seller_trades', to=settings.AUTH_USER_MODEL, verbose_name='Seller')),
            ],
            options={
                'verbose_name_plural': 'Trades',
            },
        ),
        migrations.CreateModel(
            name='TradeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_trade_items', to='trade.trade', verbose_name='Trade')),
                ('user_plant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='get_trade_items', to='plant.userplant', verbose_name='User Plant')),
            ],
            options={
                'verbose_name_plural': 'Trade Items',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('message_sent_time', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Message Recipient')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Message Sender')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_trade_messages', to='trade.trade', verbose_name='Trade')),
            ],
            options={
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
