# Generated by Django 4.0.1 on 2022-01-27 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plant', '0006_rename_plant_id_plantcommonname_plant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('trade_status', models.CharField(choices=[('SE', 'sent'), ('AC', 'accepted'), ('RJ', 'rejected')], default='SE', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Trades',
            },
        ),
        migrations.CreateModel(
            name='TradeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getTradeItems', to='trade.trade', verbose_name='Trade')),
                ('user_plant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='getTradeItems', to='plant.userplant', verbose_name='UserPlant')),
            ],
            options={
                'verbose_name_plural': 'Trade Items',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('message_sent_time', models.DateTimeField(auto_now_add=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getTradeMessages', to='trade.trade', verbose_name='Trade')),
            ],
            options={
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
