# Generated by Django 4.0.1 on 2022-01-27 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='getUserMessages', to=settings.AUTH_USER_MODEL, verbose_name='Message Sender'),
        ),
        migrations.AddField(
            model_name='trade',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='getBuyerTrades', to=settings.AUTH_USER_MODEL, verbose_name='Buyer'),
        ),
        migrations.AddField(
            model_name='trade',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='getSellerTrades', to=settings.AUTH_USER_MODEL, verbose_name='Seller'),
        ),
    ]
