# Generated by Django 4.0.1 on 2022-02-01 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_trade_messages', to='trade.trade', verbose_name='Trade'),
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
