# Generated by Django 4.0.1 on 2022-02-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_rename_thread_message_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_status',
            field=models.CharField(choices=[('SE', 'sent'), ('AC', 'accepted'), ('RE', 'rejected'), ('UN', 'unavailable')], default='SE', max_length=2),
        ),
    ]
