# Generated by Django 4.0.1 on 2022-02-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='accepted_handling_method',
            field=models.CharField(choices=[('UN', 'Undefined'), ('SH', 'Ship'), ('PI', 'Pickup')], default='UN', max_length=2),
        ),
        migrations.AddField(
            model_name='trade',
            name='is_offered_for_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='is_offered_for_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
