# Generated by Django 4.0.1 on 2022-02-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_status',
            field=models.CharField(choices=[('SE', 'Sent'), ('AC', 'Accepted'), ('RE', 'Rejected'), ('UN', 'Unavailable')], default='SE', max_length=2),
        ),
    ]
