# Generated by Django 4.0.1 on 2022-03-05 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_options'),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='address',
        ),
        migrations.AddField(
            model_name='trade',
            name='requester_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_trade_requester_address', to='order.address', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='trade',
            name='seller_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_trade_seller_address', to='order.address', verbose_name='Address'),
        ),
    ]
