# Generated by Django 4.0.1 on 2022-02-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_alter_trade_trade_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeitem',
            name='chosen_flag',
            field=models.BooleanField(default=None),
        ),
    ]
