# Generated by Django 4.0.1 on 2022-02-28 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_status'),
        ('trade', '0002_trade_accepted_handling_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_trade_address', to='order.address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='accepted_handling_method',
            field=models.CharField(choices=[('UN', 'Undefined'), ('SH', 'Shipping'), ('PI', 'Pickup')], default='UN', max_length=2),
        ),
    ]
