# Generated by Django 4.0.1 on 2022-02-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_tradeitem_chosen_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeitem',
            name='chosen_flag',
            field=models.BooleanField(),
        ),
    ]
