# Generated by Django 4.0.1 on 2022-01-27 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(help_text='Describe the plant')),
                ('plant_care', models.TextField(help_text='Share some care info\nLight:\nWater:\nFertilizer:\nTemperature:\nHumidity:\nSoil:\nPot:\nPruning:\nPropagation:\nPoisonous Plant Info:\n')),
            ],
            options={
                'verbose_name_plural': 'Plants',
            },
        ),
        migrations.CreateModel(
            name='UserPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_for_sale', models.BooleanField(default=False)),
                ('is_for_trade', models.BooleanField(default=False)),
                ('is_for_pickup', models.BooleanField(default=False)),
                ('is_for_shipping', models.BooleanField(default=False)),
                ('image_url', models.CharField(blank=True, max_length=512)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('comment', models.TextField(blank=True, help_text='Share some info about your plant!')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='get_user_plants', to='plant.plant', verbose_name='Plant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_user_plants', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': "User's Plants",
            },
        ),
        migrations.CreateModel(
            name='PlantCommonName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_common_names', to='plant.plant', verbose_name='Plant')),
            ],
            options={
                'verbose_name_plural': 'Plant Common Names',
            },
        ),
    ]
