# Generated by Django 4.0.1 on 2022-02-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='deleted_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
