# Generated by Django 4.0.1 on 2022-02-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_userplant_deleted_by_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='userplant',
            name='tags',
            field=models.ManyToManyField(to='plant.Tag'),
        ),
    ]
