# Generated by Django 4.0.1 on 2022-02-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_tag_userplant_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplant',
            name='tags',
            field=models.ManyToManyField(blank=True, to='plant.Tag'),
        ),
    ]
