# Generated by Django 4.0.1 on 2022-02-14 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_alter_userplant_tags'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plantcommonname',
            unique_together={('name', 'plant')},
        ),
    ]
