# Generated by Django 4.0.1 on 2022-01-30 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_managers'),
        ('user', '0002_customuser_badges_customuser_location_and_more'),
    ]

    operations = [
    ]
