# Generated by Django 4.0.1 on 2022-02-22 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='address_for_pickup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='get_order_pickup_address', to='order.address', verbose_name='Pickup address'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_for_shipping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='get_order_shipping_address', to='order.address', verbose_name='Ship to address'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='CR', max_length=2),
        ),
    ]
