# Generated by Django 4.0.1 on 2022-02-22 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0004_order_handling_alter_order_address_for_pickup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='canceled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Canceled by user'),
        ),
        migrations.AddField(
            model_name='order',
            name='canceled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
